{{- if eq (include "acm.ishubcluster" .) "true" }}
{{- range .Values.clusterGroup.managedClusterGroups }}
{{- $group := . }}
---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
 name: {{ .name }}-argocdagent
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  placementRef:
    kind: Placement
    name: {{ .name }}-argocdagent-placement
  argoServer:
    cluster: local-cluster
    argoNamespace: openshift-gitops
  gitopsAddon:
    enabled: true
    argoCDAgent:
      enabled: true
      mode: managed
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ .name }}-argocdagent-placement
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
{{- include "acm.app.clusterSelector" (dict
  "clusterSelector" .clusterSelector
  "group" $group
  ) | nindent 2 }}
{{- end }}{{/* range .Values.clusterGroup.managedClusterGroups */}}
{{- end }}{{/* ishubcluster */}}
